"""
HTML tag factories (PascalCase Python names; element names follow HTML).

Import from the markup namespace:

    from stario.markup import html as h

Then e.g. `h.Div(...)`. Attribute and child rules match SVG tags (same
`Tag` implementation). Void elements (`Br`, `Img`, `Input`, …) use
`empty="void"`: they render as `<tag/>` and reject children.

For full pages use `h.HtmlDocument` (`<!doctype html>` + `<html>`). Use
`h.Html` for fragments, tests, and benchmarks (`<html>` only).
"""

from .tag import Tag as _Tag

Html = _Tag("html")
HtmlDocument = _Tag("html", prefix="<!doctype html>")

A = _Tag("a")
Abbr = _Tag("abbr")
Address = _Tag("address")
Area = _Tag("area", empty="void")
Article = _Tag("article")
Aside = _Tag("aside")
Audio = _Tag("audio")
B = _Tag("b")
Base = _Tag("base", empty="void")
Bdi = _Tag("bdi")
Bdo = _Tag("bdo")
Blockquote = _Tag("blockquote")
Body = _Tag("body")
Br = _Tag("br", empty="void")
Button = _Tag("button")
Canvas = _Tag("canvas")
Caption = _Tag("caption")
Cite = _Tag("cite")
Code = _Tag("code")
Col = _Tag("col", empty="void")
Colgroup = _Tag("colgroup")
Data = _Tag("data")
Datalist = _Tag("datalist")
Dd = _Tag("dd")
Del = _Tag("del")
Details = _Tag("details")
Dfn = _Tag("dfn")
Dialog = _Tag("dialog")
Div = _Tag("div")
Dl = _Tag("dl")
Dt = _Tag("dt")
Em = _Tag("em")
Embed = _Tag("embed", empty="void")
Fieldset = _Tag("fieldset")
Figcaption = _Tag("figcaption")
Figure = _Tag("figure")
Footer = _Tag("footer")
Form = _Tag("form")
H1 = _Tag("h1")
H2 = _Tag("h2")
H3 = _Tag("h3")
H4 = _Tag("h4")
H5 = _Tag("h5")
H6 = _Tag("h6")
Head = _Tag("head")
Header = _Tag("header")
Hgroup = _Tag("hgroup")
Hr = _Tag("hr", empty="void")
I = _Tag("i")  # noqa: E741
Iframe = _Tag("iframe")
Img = _Tag("img", empty="void")
Input = _Tag("input", empty="void")
Ins = _Tag("ins")
Kbd = _Tag("kbd")
Label = _Tag("label")
Legend = _Tag("legend")
Li = _Tag("li")
Link = _Tag("link", empty="void")
Main = _Tag("main")
Map = _Tag("map")
Mark = _Tag("mark")
Math = _Tag("math")
Menu = _Tag("menu")
Meta = _Tag("meta", empty="void")
Meter = _Tag("meter")
Nav = _Tag("nav")
Noscript = _Tag("noscript")
Object = _Tag("object")
Ol = _Tag("ol")
Optgroup = _Tag("optgroup")
Option = _Tag("option")
Output = _Tag("output")
P = _Tag("p")
Param = _Tag("param", empty="void")
Picture = _Tag("picture")
Pre = _Tag("pre")
Progress = _Tag("progress")
Q = _Tag("q")
Rp = _Tag("rp")
Rt = _Tag("rt")
Ruby = _Tag("ruby")
S = _Tag("s")
Samp = _Tag("samp")
Script = _Tag("script")
Search = _Tag("search")
Section = _Tag("section")
Select = _Tag("select")
Slot = _Tag("slot")
Small = _Tag("small")
Source = _Tag("source", empty="void")
Span = _Tag("span")
Strong = _Tag("strong")
Style = _Tag("style")
Sub = _Tag("sub")
Summary = _Tag("summary")
Sup = _Tag("sup")
Table = _Tag("table")
Tbody = _Tag("tbody")
Td = _Tag("td")
Template = _Tag("template")
Textarea = _Tag("textarea")
Tfoot = _Tag("tfoot")
Th = _Tag("th")
Thead = _Tag("thead")
Time = _Tag("time")
Title = _Tag("title")
Tr = _Tag("tr")
Track = _Tag("track", empty="void")
U = _Tag("u")
Ul = _Tag("ul")
Var = _Tag("var")
Video = _Tag("video")
Wbr = _Tag("wbr", empty="void")
