"""HTML tags and the document helper."""

from .tag import Tag as _Tag
from .types import SafeString as _SafeString

Html = _Tag("html")
HtmlDocument = _Tag("html")
HtmlDocument.tag_start = "<!doctype html><html"
HtmlDocument.tag_start_no_attrs = "<!doctype html><html>"
HtmlDocument.closing_tag = "</html>"
HtmlDocument.no_children_close = "></html>"
HtmlDocument.rendered = _SafeString("<!doctype html><html></html>")
HtmlDocument._repr = "Tag(name='html-document', self_closing=False)"

# --- flow & text -------------------------------------------------------------

A = _Tag("a")
Abbr = _Tag("abbr")
Address = _Tag("address")
Article = _Tag("article")
Aside = _Tag("aside")
B = _Tag("b")
Bdi = _Tag("bdi")
Bdo = _Tag("bdo")
Blockquote = _Tag("blockquote")
Br = _Tag("br", True)
Button = _Tag("button")
Canvas = _Tag("canvas")
Caption = _Tag("caption")
Center = _Tag("center")
Cite = _Tag("cite")
Code = _Tag("code")
Data = _Tag("data")
Dd = _Tag("dd")
Del = _Tag("del")
Details = _Tag("details")
Dfn = _Tag("dfn")
Div = _Tag("div")
Dl = _Tag("dl")
Dt = _Tag("dt")
Em = _Tag("em")
Fieldset = _Tag("fieldset")
Figcaption = _Tag("figcaption")
Figure = _Tag("figure")
Footer = _Tag("footer")
Font = _Tag("font")
Form = _Tag("form")
H1 = _Tag("h1")
H2 = _Tag("h2")
H3 = _Tag("h3")
H4 = _Tag("h4")
H5 = _Tag("h5")
H6 = _Tag("h6")
Header = _Tag("header")
Hgroup = _Tag("hgroup")
Hr = _Tag("hr", True)
I = _Tag("i")  # noqa: E741
Iframe = _Tag("iframe")
Ins = _Tag("ins")
Kbd = _Tag("kbd")
Label = _Tag("label")
Legend = _Tag("legend")
Li = _Tag("li")
Main = _Tag("main")
Mark = _Tag("mark")
Marquee = _Tag("marquee")
Math = _Tag("math")
Menu = _Tag("menu")
Menuitem = _Tag("menuitem")
Meter = _Tag("meter")
Nav = _Tag("nav")
Noscript = _Tag("noscript")
Ol = _Tag("ol")
Optgroup = _Tag("optgroup")
Option = _Tag("option")
Output = _Tag("output")
P = _Tag("p")
Picture = _Tag("picture")
Pre = _Tag("pre")
Progress = _Tag("progress")
Q = _Tag("q")
Rp = _Tag("rp")
Rt = _Tag("rt")
Ruby = _Tag("ruby")
S = _Tag("s")
Samp = _Tag("samp")
Search = _Tag("search")
Section = _Tag("section")
Select = _Tag("select")
Small = _Tag("small")
Span = _Tag("span")
Strike = _Tag("strike")
Strong = _Tag("strong")
Sub = _Tag("sub")
Summary = _Tag("summary")
Sup = _Tag("sup")
Time = _Tag("time")
U = _Tag("u")
Ul = _Tag("ul")
Var = _Tag("var")
Wbr = _Tag("wbr", self_closing=True)

# --- document head / metadata -------------------------------------------------

Base = _Tag("base", True)
Body = _Tag("body")
Head = _Tag("head")
Link = _Tag("link", True)
Meta = _Tag("meta", True)
Script = _Tag("script")
Style = _Tag("style")
Title = _Tag("title")

# --- embedded & media --------------------------------------------------------

Area = _Tag("area", True)
Audio = _Tag("audio")
Embed = _Tag("embed", True)
Img = _Tag("img", True)
Object = _Tag("object")
Param = _Tag("param", True)
Source = _Tag("source", True)
Track = _Tag("track", True)
Video = _Tag("video")

# --- tables ------------------------------------------------------------------

Table = _Tag("table")
Tbody = _Tag("tbody")
Td = _Tag("td")
Tfoot = _Tag("tfoot")
Th = _Tag("th")
Thead = _Tag("thead")
Tr = _Tag("tr")

# --- forms -------------------------------------------------------------------

Input = _Tag("input", True)
Textarea = _Tag("textarea")
Col = _Tag("col", True)
Colgroup = _Tag("colgroup")
Datalist = _Tag("datalist")
Dialog = _Tag("dialog")
Template = _Tag("template")
