"""Typing for the Cython header pair list.

Runtime ``Headers`` is ``stario_cython.exchange.Headers``. This module exists so
IDEs and typecheckers see the application API. There is no Python implementation.
"""

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:

    @runtime_checkable
    class Headers(Protocol):
        def add(self, name: str, value: str) -> None: ...
        def set(self, name: str, value: str) -> None: ...
        def setdefault(self, name: str, value: str) -> str: ...
        def get(self, name: str, default: str | None = None) -> str | None: ...
        def getlist(self, name: str) -> list[str]: ...
        def remove(self, name: str) -> None: ...
        def items(self) -> list[tuple[str, str]]: ...
        def unsafe_add(self, name: bytes, value: bytes) -> None: ...
        def unsafe_set(self, name: bytes, value: bytes) -> None: ...
        def unsafe_get(self, name: bytes, default: bytes | None = None) -> bytes | None: ...
        def unsafe_getlist(self, name: bytes) -> list[bytes]: ...
        def unsafe_remove(self, name: bytes) -> None: ...
        def unsafe_items(self) -> list[tuple[bytes, bytes]]: ...
        def __contains__(self, name: object) -> bool: ...
        def __bool__(self) -> bool: ...
        def __len__(self) -> int: ...

    def encode_header_value(value: str) -> bytes: ...

else:
    from stario_cython.exchange import Headers, encode_header_value

__all__ = ["Headers", "encode_header_value"]
