def brotli_compress(data: bytes, level: int = 4, window: int = 0) -> bytes: ...
def brotli_decompress(data: bytes) -> bytes: ...
def zstd_compress(data: bytes, level: int = 3, window: int = 0) -> bytes: ...
def zstd_decompress(data: bytes) -> bytes: ...

class BrotliEncoder:
    def __init__(self, level: int, window: int = 0) -> None: ...
    def block(self, data: bytes) -> bytes: ...
    def finish(self, data: bytes = b"") -> bytes: ...

class ZstdEncoder:
    def __init__(self, level: int, window: int = 0) -> None: ...
    def block(self, data: bytes) -> bytes: ...
    def finish(self, data: bytes = b"") -> bytes: ...

class BrotliDecoder:
    def decompress(self, data: bytes) -> bytes: ...
    def is_finished(self) -> bool: ...

class ZstdDecoder:
    def decompress(self, data: bytes) -> bytes: ...
    def is_finished(self) -> bool: ...
