from collections.abc import AsyncIterator, Iterator, Mapping
from typing import overload

from stario.http.context import Handler, Match
from stario.http.route import Route

class Headers:
    def __init__(
        self,
        raw_header_data: Mapping[str, str | list[str]]
        | Mapping[bytes, bytes | list[bytes]]
        | None = None,
    ) -> None: ...
    def add(self, name: str, value: str) -> None: ...
    def set(self, name: str, value: str) -> None: ...
    def setdefault(self, name: str, value: str) -> str: ...
    @overload
    def get(self, name: str) -> str | None: ...
    @overload
    def get(self, name: str, default: str) -> str: ...
    @overload
    def get(self, name: str, default: str | None) -> str | None: ...
    def getlist(self, name: str) -> list[str]: ...
    def remove(self, name: str) -> None: ...
    def items(self) -> list[tuple[str, str]]: ...
    def unsafe_add(self, name: bytes, value: bytes) -> None: ...
    def unsafe_set(self, name: bytes, value: bytes) -> None: ...
    @overload
    def unsafe_get(self, name: bytes) -> bytes | None: ...
    @overload
    def unsafe_get(self, name: bytes, default: bytes) -> bytes: ...
    @overload
    def unsafe_get(self, name: bytes, default: bytes | None) -> bytes | None: ...
    def unsafe_getlist(self, name: bytes) -> list[bytes]: ...
    def unsafe_remove(self, name: bytes) -> None: ...
    def unsafe_items(self) -> list[tuple[bytes, bytes]]: ...
    def __contains__(self, name: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...

def encode_header_value(value: str) -> bytes: ...

class RequestHeaders:
    """Read-only request headers (``c.req.headers``)."""

    def __init__(
        self,
        headers: Headers
        | Mapping[str, str | list[str]]
        | Mapping[bytes, bytes | list[bytes]]
        | None = None,
    ) -> None: ...
    @overload
    def get(self, name: str) -> str | None: ...
    @overload
    def get(self, name: str, default: str) -> str: ...
    @overload
    def get(self, name: str, default: str | None) -> str | None: ...
    def getlist(self, name: str) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    @overload
    def unsafe_get(self, name: bytes) -> bytes | None: ...
    @overload
    def unsafe_get(self, name: bytes, default: bytes) -> bytes: ...
    @overload
    def unsafe_get(self, name: bytes, default: bytes | None) -> bytes | None: ...
    def unsafe_getlist(self, name: bytes) -> list[bytes]: ...
    def unsafe_items(self) -> list[tuple[bytes, bytes]]: ...
    def __contains__(self, name: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...

class ParsedQuery:
    def __init__(self, raw: bytes = b"") -> None: ...
    @overload
    def get(self, key: str) -> str | None: ...
    @overload
    def get[T](self, key: str, default: T) -> str | T: ...
    def getlist(self, key: str) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def as_dict(self, *, last: bool = False) -> dict[str, str]: ...
    def as_lists(self) -> dict[str, list[str]]: ...
    def __contains__(self, key: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...

class ParsedCookies:
    def __init__(self, lines: list[str] | None = None) -> None: ...
    @overload
    def get(self, name: str) -> str | None: ...
    @overload
    def get(self, name: str, default: str) -> str: ...
    @overload
    def get(self, name: str, default: str | None) -> str | None: ...
    def as_dict(self) -> dict[str, str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def __getitem__(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, name: object) -> bool: ...

class Request:
    method: str
    path: str
    """Fully percent-decoded path (``%2F`` becomes ``/``)."""
    @property
    def headers(self) -> RequestHeaders: ...
    protocol_version: str
    keep_alive: bool
    def __init__(
        self,
        *,
        method: str = "GET",
        path: str = "/",
        query_bytes: bytes = b"",
        protocol_version: str = "1.1",
        keep_alive: bool = True,
        headers: RequestHeaders
        | Headers
        | Mapping[str, str | list[str]]
        | Mapping[bytes, bytes | list[bytes]]
        | None = None,
        body: bytes | None = None,
        raw_path: bytes | None = None,
    ) -> None: ...
    @property
    def raw_path(self) -> bytes:
        """Path exactly as sent: percent-encoded, no query. Routing uses this."""
    @property
    def query_bytes(self) -> bytes: ...
    @property
    def host(self) -> str: ...
    @property
    def query(self) -> ParsedQuery: ...
    @property
    def cookies(self) -> ParsedCookies: ...
    async def body(self, max_size: int | None = None) -> bytes: ...
    def stream(self, max_chunk: int | None = None) -> AsyncIterator[bytes]: ...

class CRouter:
    def lookup(
        self, host: str, path: str, method: str
    ) -> tuple[Handler, Route, Match]: ...

class AppState:
    host_routing: bool
    shutting_down: bool
    router: CRouter | None

def compile_router(router: object) -> CRouter: ...
def canonical_request_path(raw: bytes) -> tuple[int, bytes | None]: ...
def decode_request_path(raw: bytes) -> str: ...
def host_without_port(host: str) -> str: ...
def _retained_detach_count() -> int: ...
